//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.Envelopes = new HashSet<Envelope>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual ICollection<Envelope> Envelopes { get; set; }
    }
}
