//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envelope
    {
        public int Id { get; set; }
        public int BudgetId { get; set; }
        public string Name { get; set; }
        public double Capacity { get; set; }
        public double Balance { get; set; }
        public System.Guid Guid { get; set; }
    }
}
